### ISSUE TITLE
Diagram layout not preserved

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#120]
I was leaving the diagram in Ontographer as per 
![image](https://user-images.githubusercontent.com/1140626/95719775-9b853180-0c70-11eb-9229-82a2ff039d00.png)

When @martinnec opened the diagram, he saw
![image](https://user-images.githubusercontent.com/1140626/95719815-a9d34d80-0c70-11eb-9c48-8e4fe447f950.png)

**Comment by bindetad** [comment]
In fca1208, I have modified the relevant code and was able to create diagrams with tens of elements without issue, so presumably after re-positioning the elements again, this should be fixed.

**Comment by psiotwo** [comment]
Tried on https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1269492277 and having still the same problem

![image](https://user-images.githubusercontent.com/1140626/95983910-af709500-0e22-11eb-8ca3-631cae375027.png)
![image](https://user-images.githubusercontent.com/1140626/95983919-b3041c00-0e22-11eb-809c-770adcb98f74.png)

**Comment by psiotwo** [comment]
Related problem is that some of the nodes I hid and edges I deleted reappear once I open the diagram again (tried open the second ontographer in incognito mode)

**Comment by bindetad** [comment]
In 28081f3, layouting triggers have been rewritten, so that now, hopefully:
- Saving layouting changes is much faster.
- The relevant triples are only touched when they need to be changed.
- There were some issues with fetching the right coordinates - that is fixed now.

Try hiding and repositioning the concept again when testing - I noticed some dirty triples when debugging, which will hopefully be reset when hiding.

**Comment by psiotwo** [comment]
Changing only relevant triples apparently made it much better.

For the changed triples I can still see layouting issues with intermediate edge points, see below.

After saving in one tab:
![image](https://user-images.githubusercontent.com/1140626/97835712-158e6080-1cdb-11eb-8ff7-bacbb23f781d.png)

After loading in another tab:
![image](https://user-images.githubusercontent.com/1140626/97835682-03142700-1cdb-11eb-9bba-873206381011.png)

**Comment by bindetad** [comment]
The aforementioned issue is related to the "orange" issue in #141. In d233aab, this seems to be resolved (Newly moved vertices are updated as they should).

**Comment by psiotwo** [comment]
OK, the rest seems to work, so closing this one in favour of #141.
