### ISSUE TITLE
When I switch to compact view, the relator is rendered both as a link and as a node.

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#99]
When I switch to compact view, the relator is rendered both as a link and as a node. I would expect to see only the link (and not the node). 

![image](https://user-images.githubusercontent.com/1140626/92651848-48c0fe80-f2ed-11ea-8822-00c13ffc73ec.png)

**Comment by bindetad** [comment]
As of b2966b2, this issue should be resolved.

**Comment by psiotwo** [comment]
Tested on on https://ontographer.netlify.app/ - still having the issue - see e.g. https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance69809529

**Comment by bindetad** [comment]
I can't seem to reproduce the issue. I tried it with various Vs-GoV connections like these: 
![image](https://user-images.githubusercontent.com/56399637/93202866-b8067a80-f753-11ea-8a9a-8124fa2f9e77.png)
![image](https://user-images.githubusercontent.com/56399637/93202883-be94f200-f753-11ea-978a-7ea5e5f99a13.png)

**Comment by psiotwo** [comment]
OK, Works for me.
